# See: https://taskfile.dev/api/

version: "3"

tasks:
  migrate:
    aliases:
      - migrate
    desc: "Migrate SQLite DB"
    cmds:
      - go run ./cmd/migrator/main.go --storage-path=storage/sso.db --migrations-path=migrations